package com.bullythetrousse.core

// FICHIER GÉNÉRÉ depuis ACHIEVEMENTS (index.html) : pour chaque succès, les
// clés de traduction de son nom et de sa description (voir I18n).

val ACHIEVEMENT_KEYS: Map<String, Pair<String, String>> = mapOf(
    "premierLancer" to ("achvFirstThrowName" to "achvFirstThrowDesc"),
    "cent100m" to ("achv100mName" to "achv100mDesc"),
    "cinq500m" to ("achv500mName" to "achv500mDesc"),
    "mille1000m" to ("achv1000mName" to "achv1000mDesc"),
    "mille1500m" to ("achv1500mName" to "achv1500mDesc"),
    "deuxMille2000m" to ("achv2000mName" to "achv2000mDesc"),
    "quatreMille4000m" to ("achv4000mName" to "achv4000mDesc"),
    "dixMille10000m" to ("achv10000mName" to "achv10000mDesc"),
    "lancerParfait" to ("achvPerfectName" to "achvPerfectDesc"),
    "volcanDebloque" to ("achvVolcanName" to "achvVolcanDesc"),
    "claquettes" to ("achvClaquettesName" to "achvClaquettesDesc"),
    "plageDebloquee" to ("achvPlageName" to "achvPlageDesc"),
    "retourDeVacances" to ("achvBusName" to "achvBusDesc"),
    "plageLancers" to ("achvPlageThrowsName" to "achvPlageThrowsDesc"),
    "plage500m" to ("achvPlage500Name" to "achvPlage500Desc"),
    "plage2000m" to ("achvPlage2000Name" to "achvPlage2000Desc"),
    "plageEconomies" to ("achvPlageMoneyName" to "achvPlageMoneyDesc"),
    "parasols25" to ("achvParasolName" to "achvParasolDesc"),
    "serviettes20" to ("achvTowelsName" to "achvTowelsDesc"),
    "chateaux15" to ("achvCastlesName" to "achvCastlesDesc"),
    "trousseCassee" to ("achvBrokenName" to "achvBrokenDesc"),
    "collectionneur" to ("achvCollectorName" to "achvCollectorDesc"),
    "riche5000" to ("achvRichName" to "achvRichDesc"),
    "jackpotX5" to ("achvJackpotName" to "achvJackpotDesc"),
    "joueurAssidu" to ("achvDedicatedName" to "achvDedicatedDesc"),
    "cinquanteLancers" to ("achv50ThrowsName" to "achv50ThrowsDesc"),
    "centLancers" to ("achv100ThrowsName" to "achv100ThrowsDesc"),
    "cacaCache" to ("achvPoopName" to "achvPoopDesc"),
    "toutesTrainees" to ("achvAllTrailsName" to "achvAllTrailsDesc"),
    "easterEggEspace" to ("achvSpaceEggName" to "achvSpaceEggDesc"),
    "qteParfait" to ("achvPerfectQteName" to "achvPerfectQteDesc"),
    "millionnaire" to ("achvMillionaireName" to "achvMillionaireDesc"),
    "cinqCentsLancers" to ("achv500ThrowsName" to "achv500ThrowsDesc"),
    "marathonien" to ("achvMarathonName" to "achvMarathonDesc"),
    "niveau50" to ("achvLevel50Name" to "achvLevel50Desc"),
    "defisAccomplis" to ("achvDailyChallengesName" to "achvDailyChallengesDesc"),
    "grandDonateur" to ("achvGifterName" to "achvGifterDesc"),
    "adorateurMusique" to ("achvMusicName" to "achvMusicDesc"),
    "etourdi" to ("achvForgetfulName" to "achvForgetfulDesc"),
    "vingtMille20000m" to ("achv20000mName" to "achv20000mDesc"),
    "cinquanteMille50000m" to ("achv50000mName" to "achv50000mDesc"),
    "multiMillionnaire" to ("achvMultiMillionaireName" to "achvMultiMillionaireDesc"),
    "changeDeTete" to ("achvAvatarName" to "achvAvatarDesc"),
    "plage5000" to ("achvPlage5000Name" to "achvPlage5000Desc"),
    "milleLancers" to ("achv1000ThrowsName" to "achv1000ThrowsDesc"),
    "niveau100" to ("achvLevel100Name" to "achvLevel100Desc"),
    "secretTrouve" to ("achvSecretName" to "achvSecretDesc"),
)
